-- Create admin users table
CREATE TABLE IF NOT EXISTS admin_users (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create projects table
CREATE TABLE IF NOT EXISTS projects (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  tags TEXT[] NOT NULL,
  github_url TEXT,
  live_url TEXT,
  image_url TEXT NOT NULL,
  alt_text TEXT NOT NULL,
  display_order INTEGER DEFAULT 0,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

-- Policies for admin_users (restrict access)
CREATE POLICY "Admin users can view their own data"
  ON admin_users FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Policies for projects (allow public read, authenticated write)
CREATE POLICY "Allow public read access to published projects"
  ON projects FOR SELECT
  USING (is_published = true);

CREATE POLICY "Allow authenticated users to manage projects"
  ON projects FOR ALL
  USING (auth.uid() IS NOT NULL);

-- Insert default admin user (password: Fg@112233@Hadi)
-- Note: You'll need to hash this password using bcrypt before inserting
-- The hash will be generated by the initialization script
INSERT INTO admin_users (email, password_hash) 
VALUES ('preabdulhadi@gmail.com', '$2a$10$YourHashedPasswordHere')
ON CONFLICT (email) DO NOTHING;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_projects_display_order ON projects(display_order);
CREATE INDEX IF NOT EXISTS idx_projects_published ON projects(is_published);
CREATE INDEX IF NOT EXISTS idx_admin_users_email ON admin_users(email);
